const UPDATE_COLUMN = 'UPDATE_COLUMN'
const SELECT_PROJECT = 'SELECT_PROJECT'
const CREATE_PROJECT = 'CREATE_PROJECT'
const ADD_TYPE = 'ADD_TYPE'

export { UPDATE_COLUMN, SELECT_PROJECT, CREATE_PROJECT, ADD_TYPE }
